#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]
    common: [build, release]
    client-java: [build, release]

build:
  quality:
    filter:
      owner: graknlabs
      branch: master
    dependency-analysis:
      image: graknlabs-ubuntu-20.04
      command: |
        bazel run @graknlabs_dependencies//grabl/analysis:dependency-analysis
  correctness:
    build:
      image: graknlabs-ubuntu-20.04
      command: |
        bazel build //...
        bazel run @graknlabs_dependencies//tool/checkstyle:test-coverage
        bazel test $(bazel query 'kind(checkstyle_test, //...)') --test_output=streamed
    build-dependency:
      image: graknlabs-ubuntu-20.04
      command: |
        dependencies/maven/update.sh
        git diff --exit-code dependencies/maven/artifacts.snapshot
        bazel run @graknlabs_dependencies//tool/unuseddeps:unused-deps -- list
    run-grakn-core:
      machine: 64-core-128-gb
      image: graknlabs-ubuntu-20.04-512-gb
      type: background
      filter:
        owner: graknlabs
        branch: migrator
      command: |
        bazel run @graknlabs_dependencies//tool/util:create-systemd-service -- grakn-core "\/home\/grabl\/$GRABL_REPO\/dist\/grakn-core-all-linux\/grakn server"
        bazel run //:grakn-core-extractor-linux -- dist/grakn-core-all-linux
        cd ./dist/grakn-core-all-linux/

        sudo systemctl daemon-reload
        sudo systemctl start grakn-core
        export GRABL_EXPORT_GRAKN_CORE_ADDRESS="${HOSTNAME}:1729"
      monitor: |
        sleep 10s
        tail -f -n +1 /home/grabl/$GRABL_REPO/dist/grakn-core-all-linux/server/logs/grakn.log
    run-biograkn-semmed:
      machine: 8-core-16-gb
      image: graknlabs-ubuntu-20.04-semmed
      type: background
      filter:
        owner: graknlabs
        branch: migrator
      dependencies: [run-grakn-core]
      command: |
        bazel run //:migrator -- \
        --source /opt/data \
        --grakn $GRABL_EXPORT_GRAKN_CORE_ADDRESS \
        --parallelisation 64 \
        --batch 64
